name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-wheel openjdk-8-jdk libncurses6 libssl-dev wget unzip zip
          pip install --upgrade pip
          pip install cython buildozer

      - name: Install Android SDK and Build Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d temp
          # Mover o conteúdo extraído para o diretório correto
          mv temp/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm -rf temp
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0" \
            "ndk;21.4.7075529"

      - name: Build with Buildozer
        run: |
          export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/31.0.0:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4.1.0
        with:
          name: myapp-apk
          path: ./bin/*.apk
